キャッシュの設定変更など

diff --git a/.github/workflows/ios_build.yml b/.github/workflows/ios_build.yml
--- a/.github/workflows/ios_build.yml
+++ b/.github/workflows/ios_build.yml
@@ -26,6 +26,12 @@ jobs:
           path: ios/Pods
           key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
 
+      - uses: actions/cache@v1
+        id: flutter-cache
+        with:
+          path: $FLUTTER_HOME
+          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.lock') }}
+
       - name: Flutter build
         run: |
           flutter pub get
@@ -34,6 +40,9 @@ jobs:
       - uses: actions/setup-node@v1
         with:
           node-version: '10.x'
+
+      - name: install firebase-tools
+        run: npm install -g firebase-tools
 
       - name: Select Xcode version
         run: cd ios && sudo xcode-select -s '/Applications/Xcode_11.2.1.app'
@@ -69,11 +78,11 @@ jobs:
           echo "global node_modules"
           ls -l /usr/local/lib/node_modules || echo "not found"
           echo ""
-          echo ".npm"
-          ls -l ~/.npm || echo "not found"
+          echo "flutter"
+          ls -l $FLUTTER_HOME || echo "not found"
           echo ""
           echo "Pods"
-          ls -l Pods || echo "not found"
+          ls -l ios/Pods || echo "not found"
 
       - name: Adhoc
         env:
@@ -83,5 +92,4 @@ jobs:
           FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
         run: |
           cd ios
-          npm install -g firebase-tools
           fastlane adhoc
